docker:
  - image: circleci/python

version: 2.1
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run: pip install -r /recommender/requirements.txt
      - persist_to_workspace:
         root: .
         paths:
            - .

workflows:
  main:
    jobs:
      - build