romanzdk: &romanzdk
  docker:
    - image: circleci/python

version: 2.1
jobs:
  build:
    <<: *romanzdk
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - persist_to_workspace:
         root: .
         paths:
            - .
  deploy:
     <<: *romanzdk
     steps:
        - attach_workspace:
           at: .
        - run:
           command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"

workflows:
  version: 2.1
  build:
    jobs:
      - build